word_lists = {
    basics: [
        "Hello",
        "Yes",
        "No",
        "How are you?",
        "Hearing",
        "Deaf",
        "Sorry",
        "Again",
        "Nice Meet You",
        "Your",
        "Sign",
        "Write",
        "Please",
        "Thank you",
        "Start",
        "Finish",
        "See",
        "Look",
        "Stop",
        "See you again",
    ],
    basics2: [
        "Like",
        "Like/Same",
        "Don't like",
        "Love",
        "Know",
        "Don't know",
        "Understand",
        "Don't understand",
        "Want",
        "Don't want",
    ],
    days: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
        "Weekend",
    ],
    colours: [
        "Colours",
        "Red",
        "Yellow",
        "Blue",
        "Black",
        "Green",
        "White",
        "Pink",
        "Brown",
        "Purple",
        "Grey",
        "Gold",
        "Silver",
    ],

}