export const christmas = [
    "Santa",
    "Angel",
    "Carol",
    "Chocolate",
    "Christmas",
    "Card",
    "Cracker",
    "Dinner",
    "Lights",
    "Pudding",
    "Toys",
    "Tree",
    "Church",
    "Elf",
    "Jesus",
    "Mince Pie",
    "Present",
    "Reindeer",
    "Sleigh",
    "Snow",
    "Snowman",
    "Turkey",
    "Cracker",
]