export const illness = [
    "Cold",
    "Sore throat",
    "Cough",
    "Broken",
    "Accident",
    "Nurse",
    "Doctor",
    "Dentist",
    "Hospital",
    "Headache",
    "Stomach-ache",
    "Tooth Ache",
    "Sunburn",
    "Temperature",
    "Bruise",
    "Cut",
    "Sprain",
    "Ambulance",
]