export const timeScales = [
    "Month",
    "Next Month",
    "This Month",
    "Last Month",
    "Two Months",
    "Two months ago",
    "Tomorrow",
    "Yesterday",
    "Today",
    "Day",
    "Night",
    "Evening",
    "Morning",
    "Afternoon",
    "This week",
    "Next week",
    "Last week",
    "2 weeks",
    "2 weeks ago",
    "This year",
    "Next year",
    "Last year",
]